"""force_changes

Revision ID: 1a1423f09b53
Revises: 94121677a2e2
Create Date: 2025-06-24 14:21:38.485600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1423f09b53'
down_revision: Union[str, None] = '94121677a2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UOM', sa.Column('name', sa.String(), nullable=True))
    op.add_column('UOM', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('UOM', sa.Column('dimen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UOM', 'dimen')
    op.drop_column('UOM', 'short_name')
    op.drop_column('UOM', 'name')
    # ### end Alembic commands ###
