"""new_2

Revision ID: b6d071ace483
Revises: 1a1423f09b53
Create Date: 2025-06-26 09:30:41.251439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d071ace483'
down_revision: Union[str, None] = '1a1423f09b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UOM') as batch_op:
        batch_op.add_column(sa.Column('dimen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_uom_dimen_id',  # Явно указываем имя constraint
            'DIMENSION', 
            ['dimen_id'], 
            ['id']
        )
        batch_op.drop_column('dimen')

def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('UOM') as batch_op:
        batch_op.add_column(sa.Column('dimen', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_uom_dimen_id', type_='foreignkey')
        batch_op.drop_column('dimen_id')
    # ### end Alembic commands ###
